name: Build Subject

on:
  schedule:
    # Run “at minute 0 past every 2nd hour.” (see https://crontab.guru)
    - cron: '0 */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: ^6.32.2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: create env file
        run: |
          touch .env
          echo BANGUMI_USER=${{ secrets.BANGUMI_USER }} >> .env
      - name: Build Subject
        run: pnpm buildSubject
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto build subject